services:
  database-server:
    image: postgres:latest
    container_name: prisma_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DATABASE: 'manna'
      POSTGRES_PASSWORD: '1111'
    ports:
      - 5432:5432

  redis-server:
    image: redis:latest
    container_name: prisma_redis
    ports:
      - 6380:6380
