services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/server/app
      - ./lib:/server/lib
    ports:
      - 4030:4030
    env_file:
      - ./.env.docker

  database-server:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: 'manna'
      POSTGRES_PASSWORD: '1111'
    ports:
      - 5432:5432

  redis-server:
    image: redis:latest
    ports:
      - 6380:6380
