name: Deploy Manna Backend

on:
  push:
    branches: [deploy_test]
    paths:
      - "manna-backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      # GitHub 저장소의 소스 코드를 Actions runner에 다운로드
      - name: Checkout repository
        uses: actions/checkout@v3

      # AWS 자격 증명 설정
      # GitHub Actions runner가 AWS에 접근할 수 있도록 AWS 자격 정보를 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # ECR 로그인

      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Docker 이미지 빌드 & ECR에 Push
      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: manna
          IMAGE_TAG: latest
        run: |
          cd manna-backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # EC2에 SSH 접속하여 배포 실행
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash /home/ec2-user/manna/manna-backend/deploy.sh

      - name: Send success message
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                "embeds": [{
                  "title": "Manna Backend 배포 성공!",
                  "color": 65280,
                  "fields": [
                    { "name": "브랜치", "value": "${{ github.ref_name }}", "inline": true },
                    { "name": "작성자", "value": "${{ github.actor }}", "inline": true },
                    { "name": "커밋 메시지", "value": "${{ github.event.head_commit.message }}" },
                    { "name": "커밋 링크", "value": "[$GITHUB_SHA](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" }
                  ]
                }]
              }' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send failure message
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                "embeds": [{
                  "title": "Manna Backend 배포 실패!",
                  "color": 16711680,
                  "fields": [
                    { "name": "브랜치", "value": "${{ github.ref_name }}", "inline": true },
                    { "name": "작성자", "value": "${{ github.actor }}", "inline": true },
                    { "name": "원인", "value": "GitHub Actions 오류 발생. 로그 확인 필요." }
                  ]
                }]
              }' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
